# Mod06 NumPy Advanced Operations

# Operations

## Advanced Operations

In [3]:
import numpy as np
import pandas as pd

## Reduction Logical operators

In [4]:
np.random.seed(100)
ar=np.random.randint(1,10, size=(4,4)); ar

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [6]:
np.any(ar%2==0)           # 任一項除以2的餘數為0

True

In [8]:
np.all(ar<11)             # 全部項是否小於11

True

In [10]:
np.sum(ar < 6)            # 小於6的項總共有幾個

10

## Broadcasting

<b>Broadcasting works across dimensions</b>

In [20]:
ar=np.array([[23,24,25]]); ar

array([[23, 24, 25]])

In [21]:
ar.T

array([[23],
       [24],
       [25]])

In [22]:
ar.T+ar                             # 兩個陣列形狀不同，但符合broadcast的條件，會自動把缺項補齊再相加

array([[46, 47, 48],
       [47, 48, 49],
       [48, 49, 50]])

In [17]:
ar1 = np.array([[0, 0, 0],[1, 1, 1],[2, 2, 2],[3, 3, 3]])
ar1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [3]:
ar2=np.array([1,2,3])
ar2

array([1, 2, 3])

In [28]:
ar3=np.random.randint(5,size=(4,1))
ar3

array([[1],
       [4],
       [2],
       [3]])

In [29]:
ar1+ar2                            # row expansion

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [30]:
ar1+ar3                            # column expansion

array([[1, 1, 1],
       [5, 5, 5],
       [4, 4, 4],
       [6, 6, 6]])

## Lab

<b>有一個陣列 arr，試著運算累計乘積:
* element-wise
* row-wise
* column-wise
</b>

In [13]:
rand = np.random.RandomState(20)
arr = rand.randint(1, 11, size=(5,4))
arr

array([[ 4, 10,  5,  7],
       [ 8,  3,  1,  7],
       [ 9,  6,  4,  1],
       [ 7,  7,  1, 10],
       [ 6,  8,  6,  3]])

In [14]:
arr.cumprod()

array([          4,          40,         200,        1400,       11200,
             33600,       33600,      235200,     2116800,    12700800,
          50803200,    50803200,   355622400, -1805610496, -1805610496,
        -876235776,  -962447360,   890355712,  1047166976, -1153466368],
      dtype=int32)

In [15]:
arr.cumprod(axis=1)

array([[   4,   40,  200, 1400],
       [   8,   24,   24,  168],
       [   9,   54,  216,  216],
       [   7,   49,   49,  490],
       [   6,   48,  288,  864]], dtype=int32)

In [16]:
arr.cumprod(axis=0)

array([[    4,    10,     5,     7],
       [   32,    30,     5,    49],
       [  288,   180,    20,    49],
       [ 2016,  1260,    20,   490],
       [12096, 10080,   120,  1470]], dtype=int32)

<b>有一個陣列 x，試著計算:
* 計算有多少值小於 6
* 檢查每列有多少小於 6 的值
</b>

In [18]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [22]:
display(np.count_nonzero(x<6))
display(np.sum(x<6))

8

8

In [20]:
np.sum(x<6,axis=1)

array([4, 2, 2])

# 補充

<details>
    <summary><b>axis 與 shape</b></summary>
    <img src='./img/axis_shape.png'>
</details>

In [43]:
x = np.arange(24).reshape(2,3,4)
print(f'x.shape:{x.shape}')
print(x)

x.shape:(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


<b>另外，也可以由內往外數，最內部的第一個中括號就是axis=-1，越外面就越小(負得越多)。</b>

In [23]:
C = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(C,end='\n-------------\n')
print(np.sum(C,axis=-3),end='\n-------------\n')
print(np.sum(C,axis=0),end='\n-------------\n')
print(np.sum(C,axis=-2),end='\n-------------\n')
print(np.sum(C,axis=1),end='\n-------------\n')
print(np.sum(C,axis=-1),end='\n-------------\n')
print(np.sum(C,axis=2),end='\n-------------\n')


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
-------------
[[ 8 10 12]
 [14 16 18]]
-------------
[[ 8 10 12]
 [14 16 18]]
-------------
[[ 5  7  9]
 [17 19 21]]
-------------
[[ 5  7  9]
 [17 19 21]]
-------------
[[ 6 15]
 [24 33]]
-------------
[[ 6 15]
 [24 33]]
-------------


<b>參與運算的所有陣列必須符合以下規則才能做broadcasting，所有矩陣的shape由[axis＝-1開始]對齊去比較彼此間的數值，比較結果必須符合以下兩種規則其中之一：</b><br>
    1. 兩個陣列的相同axis的數值為同一個值<br>
    2. 如果兩個陣列的相同axis的數值為不同值，則其中一個數值必定是0或1

In [24]:
# 可以broadcast的陣列
ar1=np.random.randint(0,100,size=(8,7,1,5,9,1))
ar2=np.random.randint(0,100,size=(8,1,5,5,1,6)) 
a = ar1*ar2
a.shape

(8, 7, 5, 5, 9, 6)

In [25]:
# 可以broadcast的陣列
ar1=np.random.randint(0,100,size=(3,5)) 
ar2=np.random.randint(0,100,size=(6,2,1,3,5))
a = ar1*ar2
a.shape

(6, 2, 1, 3, 5)

In [26]:
# 不能broadcast的陣列
ar1=np.random.randint(0,100,size=(3,9)) 
ar2=np.random.randint(0,100,size=(6,2,1,3,5))
ar1*ar2

ValueError: operands could not be broadcast together with shapes (3,9) (6,2,1,3,5) 