# Mod03 Create NumPy Array

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.20.1'

## NumPy array creation via numpy.array
NumPy arrays can be created via the numpy.array constructor directly

In [3]:
ar1 = np.array([0,1,2,3]); ar1                                 

array([0, 1, 2, 3])

In [4]:
print(ar1.shape)
print(ar1.ndim)         # ndim陣列維度 
print(ar1.dtype)        # dtype陣列資料型態   整數32位元
print(ar1.size)         # 陣列元素個數
print(ar1.itemsize)     # 陣列元素大小
print(ar1.nbytes)       # 整個陣列的大小(6*4)

(4,)
1
int32
4
4
16


In [14]:
ar2 = np.array([[0,3,5],[2,8,7]], dtype='float'); ar2         # 直接指定資料型態

array([[0., 3., 5.],
       [2., 8., 7.]])

In [15]:
print(ar2.shape)
print(ar2.ndim)         # ndim陣列維度 
print(ar2.dtype)        # dtype陣列資料型態   整數32位元
print(ar2.size)         # 陣列元素個數
print(ar2.itemsize)     # 陣列元素大小
print(ar2.nbytes)       # 整個陣列的大小(6*4)

(2, 3)
2
float64
6
8
48


In [20]:
ar3 = np.array([[True,False,True],[True,True,False],[False,True,False]]); ar3                

array([[ True, False,  True],
       [ True,  True, False],
       [False,  True, False]])

In [21]:
print(ar3.shape)
print(ar3.ndim)       
print(ar3.dtype)        
print(ar3.size)         
print(ar3.itemsize)    
print(ar3.nbytes)       

(3, 3)
2
bool
9
1
9


In [23]:
ar4 = np.array([[["你","好","嗎"],["我","是","誰"]],[["很","高","興"],["見","到","你"]]]); ar4

array([[['你', '好', '嗎'],
        ['我', '是', '誰']],

       [['很', '高', '興'],
        ['見', '到', '你']]], dtype='<U1')

In [24]:
print(ar4.shape)
print(ar4.ndim)         
print(ar4.dtype)                  # <U1每一項只能是unicode 1個字，如果輸入大於1個字就會印不出來   
print(ar4.size)         
print(ar4.itemsize)     
print(ar4.nbytes)       

(2, 2, 3)
3
<U1
12
4
48


In [26]:
s_ar = ar4.astype("<U2")         # astype()改變資料型態
print(s_ar)      
print(s_ar.dtype)

[[['你' '好' '嗎']
  ['我' '是' '誰']]

 [['很' '高' '興']
  ['見' '到' '你']]]
<U2


## NumPy array creation via numpy.arange
ndarray.arange is the NumPy version of Python's range function

In [5]:
ar5=np.arange(12)
ar5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
ar6=np.arange(5,10)
ar6  

array([5, 6, 7, 8, 9])

In [7]:
# start, end (exclusive)
ar7=np.arange(3,10,3)
ar7

array([3, 6, 9])

## NumPy array via various other functions
These functions include numpy.zeros, numpy.ones, numpy.eye, nrandom.rand,
numpy.random.randn, and numpy.empty

In [3]:
# 在指定的間隔內返回均勻間隔的數字
# args - start element,end element, number of elements
ar6=np.linspace(0,6,4)
ar6

array([0., 2., 4., 6.])

In [57]:
# empty()創建的是一個空陣列
ar13=np.empty((3,2)); ar13   

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
# Produce 4x2 array of zeros.
ar8=np.zeros((4,2)); ar8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
# Produces 2x3x2 array of 1's.
ar7=np.ones((2,3,2)); ar7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [13]:
# Produces identity matrix  對角矩陣
ar9 = np.eye(3); ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.random.rand

In [37]:
# 隨機產生0~1之間的數，設定seed可以讓每次產生的數都相同
np.random.seed(200)
ar11=np.random.rand(2,3); ar11

array([[0.94763226, 0.22654742, 0.59442014],
       [0.42830868, 0.76414069, 0.00286059]])

In [4]:
# randn(m) produces m normally distributed (Gaussian) random numbers
# rand()產生的數可能為正可能為負
ar12=np.random.randn(5,); ar12

array([-0.76987279, -0.02396386, -0.74781035, -1.93557602, -0.60791416])

In [39]:
# 產生100內的整數
ar13=np.random.randint(100,size=(7,)); ar13

array([ 7, 22, 54, 77, 16, 70, 35])

## Lab

<b> 利用 arange() 建立一個 array([11, 14, 17, 20]) 的陣列 <b>

In [40]:
nda = np.arange(11,21,3);nda

array([11, 14, 17, 20])

<b>建立一個陣列如下，並列出陣列形狀與維度
```
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
```
</b>


In [172]:
nda1 = np.array([[[1,2,3,4],[5,6,7,8]]
                ,[[9,10,11,12],[13,14,15,16]]
                ,[[17,18,19,20],[21,22,23,24]]])
print(nda1)
print("-"*50)
print("shape = ",nda1.shape)
print("-"*50)
print("ndim = ",nda1.ndim)
print("-"*50)
print("dtype = ",nda1.dtype)
print("-"*50)
print("size = ",nda1.size)
print("-"*50)
print("itemsize = ",nda1.itemsize)
print("-"*50)
print("nbytes = ",nda1.nbytes)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
--------------------------------------------------
shape =  (3, 2, 4)
--------------------------------------------------
ndim =  3
--------------------------------------------------
dtype =  int32
--------------------------------------------------
size =  24
--------------------------------------------------
itemsize =  4
--------------------------------------------------
nbytes =  96


In [5]:
nda2 = np.arange(1,25).reshape(3,2,4)
nda2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])