# Mod05 NumPy Basic Operations

# Operations

Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated operations on values in NumPy arrays.<br>
Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary ufuncs, which operate on two inputs.

## Basic Operations

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators.<br>
The standard addition, subtraction, multiplication, and division can all be used.

<b>一維陣列運算</b>

In [1]:
import numpy as np
import pandas as pd

In [102]:
ar=np.arange(5) * 5; print(ar)
ar=np.arange(5) ** 0.5 ; print(ar)
ar=np.arange(0, 30,3) + 3; print(ar)

[ 0  5 10 15 20]
[0.         1.         1.41421356 1.73205081 2.        ]
[ 3  6  9 12 15 18 21 24 27 30]


In [103]:
ar2=np.arange(1,11); ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
print(ar+ar2)                           # 因為形狀相同所以可以直接將兩個陣列做運算
print(ar/ar2)
print(ar**ar2)

[ 4  8 12 16 20 24 28 32 36 40]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
[          3          36         729       20736      759375    34012224
  1801088541 -1593835520  2030534587   716276736]


<b>二維陣列運算</b>

In [24]:
ar=np.array([[1,2],[3,4]]); display(ar)
ar2=np.array([[2,3],[2,3]]); display(ar2)

array([[1, 2],
       [3, 4]])

array([[2, 3],
       [2, 3]])

In [25]:
ar*ar2                                   # 各項乘各項

array([[ 2,  6],
       [ 6, 12]])

In [26]:
display(np.dot(ar,ar2))                  # 矩陣乘法:1*2+2*2 1*3+2*3 3*2+4*2 3*3+4*3
display(np.matmul(ar,ar2))

array([[ 6,  9],
       [14, 21]])

array([[ 6,  9],
       [14, 21]])

In [21]:
ar=np.arange(0,6); display(ar)
ar2=np.arange(0,8); display(ar2)

array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
ar*ar2                                    # 因為形狀不同又不合broadcaste原則所以無法相乘

ValueError: operands could not be broadcast together with shapes (6,) (8,) 

<b>Comparison and logical operations are also elememt-wise</b>

In [3]:
ar=np.array([12,0,1,0]); display(ar)
ar2=np.array([1, 1, 1, 0]); display(ar2)

array([12,  0,  1,  0])

array([1, 1, 1, 0])

In [12]:
print(ar < ar2)
print(ar == ar2)
print(ar != ar2)

[False  True False False]
[False False  True  True]
[ True  True False False]


In [13]:
print(np.logical_and(ar,ar2))
print(np.logical_or(ar,ar2))
print(np.logical_xor(ar,ar2))
print(np.logical_not(ar2))

[ True False  True False]
[ True  True  True False]
[False  True False False]
[False False False  True]


<b>三元運算</b>

In [5]:
xarr = np.array(["x", "x", "x", "x", "x"])
yarr = np.array(["y", "y", "y", "y", "y"])
cond = np.array([False, True, False, False, True])

In [12]:
list(zip(xarr, yarr, cond))                                    # zip回傳的是 tuples的迭代器（iterator）

[('x', 'y', False),
 ('x', 'y', True),
 ('x', 'y', False),
 ('x', 'y', False),
 ('x', 'y', True)]

In [30]:
result = [(x if c else y)for x, y, c in zip(xarr, yarr, cond)] ; result

['y', 'x', 'y', 'y', 'x']

In [31]:
result = np.where(cond,xarr,yarr) ; display(result)             # cond為True就是xarr;cond為False就是yarr
result = np.where(cond,yarr,xarr) ; display(result)             # cond為True就是yarr;cond為False就是xarr

array(['y', 'x', 'y', 'y', 'x'], dtype='<U1')

array(['x', 'y', 'x', 'x', 'y'], dtype='<U1')

<b>NumPy arrays can be transposed</b>

In [33]:
ar=np.array([[1,2,3],[4,5,6]]); ar

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
display(ar.T)                                                   # 矩陣轉置
display(np.transpose(ar))

array([[1, 4],
       [2, 5],
       [3, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

<b>NumPy arrays can be reshaped</b>

In [126]:
ar.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [127]:
ar.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

## Axis in 2D array
<details>
    <summary>image</summary>
    <img src='./img/2D_axis_1.jpg'>
</details>

## Reduction Operations
Operators such as np.sum and np.prod perform reduces on arrays; that is, they
combine several elements into a single value:

In [154]:
ar=np.arange(1,5); ar

array([1, 2, 3, 4])

In [155]:
print(ar.prod())                            # 各項相乘
print(ar.cumprod())
print(ar.std())                             # std()標準差:一組數值與其平均值分散開來的程度

24
[ 1  2  6 24]
1.118033988749895


<b>specify whether the reduction operator to be applied row-wise or column-wise</b>
<details>
    <summary>image</summary>
    <img src='./img/2D_axis.jpg'>
</details>

In [13]:
ar=np.array([np.arange(1,6),np.arange(1,6),np.arange(1,6)]); ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [14]:
print(np.prod(ar,axis=0),end = "\n-------------------\n")     
print(np.prod(ar,axis=1),end = "\n-------------------\n")          
print(ar.cumprod(axis=0),end = "\n-------------------\n")
print(ar.cumprod(axis=1),end = "\n-------------------\n")


[  1   8  27  64 125]
-------------------
[120 120 120]
-------------------
[[  1   2   3   4   5]
 [  1   4   9  16  25]
 [  1   8  27  64 125]]
-------------------
[[  1   2   6  24 120]
 [  1   2   6  24 120]
 [  1   2   6  24 120]]
-------------------


In [15]:
print(np.sum(ar),end = "\n-------------------\n")             # 各項相加
print(ar.cumsum(),end = "\n-------------------\n")            # 各項累積之合
print(ar.cumsum(axis=0),end = "\n-------------------\n")
print(ar.cumsum(axis=1),end = "\n-------------------\n")

45
-------------------
[ 1  3  6 10 15 16 18 21 25 30 31 33 36 40 45]
-------------------
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]
-------------------
[[ 1  3  6 10 15]
 [ 1  3  6 10 15]
 [ 1  3  6 10 15]]
-------------------


In [152]:
print(np.median(ar))                                # 取中位數
print(ar.mean())                                    # 求平均值
print(ar.mean(axis=0))
print(ar.mean(axis=1))

3.0
3.0
[1. 2. 3. 4. 5.]
[3. 3. 3.]


In [153]:
print(ar.var())                                     # var()變異數:該變數離其期望值的距離
print(ar.var(axis=0)) 
print(ar.var(axis=1)) 

2.0
[0. 0. 0. 0. 0.]
[2. 2. 2.]


## Lab

<b>使用 NumPy 版的三元運算子 x if c else y，試著將兩個陣列相同位置的元素較大者取出</b>

In [133]:
xarr = np.array([1.1, 3.2, 1.3, 1.4, 5.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [134]:
np.where(xarr>yarr,xarr,yarr)

array([2.1, 3.2, 2.3, 2.4, 5.5])

<b>有一個二維陣列 data，試著:
* 求 data 的平均值
* 求每一列的平均值
* 求每一行的平均值
</b>

In [40]:
data = np.arange(6).reshape((3,2))
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
print(data.mean())
print(data.mean(axis=1))
print(data.mean(axis=0))

2.5
[0.5 2.5 4.5]
[2. 3.]
