# Mod04 Using NumPy Array

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.20.1'

## Array indexing

In [112]:
ar = 2*np.arange(5)
print(ar)

[0 2 4 6 8]


In [113]:
print(ar[0], ar[1], ar[-1])           # 個別取再放入list，資料型態是list
print(ar[[0,1,-1]])                   # Fancy index，資料型態是array
print(ar[::-1])

0 2 8
[0 2 8]
[8 6 4 2 0]


In [114]:
ar[:3]=1; print(ar)
ar[2:]=np.ones(3); print(ar)

[1 1 1 6 8]
[1 1 1 1 1]


In [17]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [18]:
print(ar[2,0], ar[2,1], ar[2,2], end="\n----------------\n")
print(ar[[0,1,2]], end="\n----------------\n")                 # Fancy index
print(ar[1,1], end="\n----------------\n")
print(ar[:,1], end="\n----------------\n")
print(ar[1,:], end="\n----------------\n")

11 12 13
----------------
[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]
----------------
8
----------------
[ 3  8 12]
----------------
[9 8 7]
----------------


In [19]:
ar[1,1]=5; ar

array([[ 2,  3,  4],
       [ 9,  5,  7],
       [11, 12, 13]])

##  Array slicing
Arrays can be sliced using the following syntax:<br>
ar[startIndex: endIndex: stepValue].

In [99]:
ar=2*np.arange(6); ar

array([ 0,  2,  4,  6,  8, 10])

In [100]:
print(ar[:4])
print(ar[4:])
print(ar[1:5:2])
print(ar[::3])

[0 2 4 6]
[ 8 10]
[2 6]
[0 6]


Assignment and slicing can be combined as shown in the following code snippet:

### Fancy Indexing

In [39]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [41]:
z = x[[3,7,2]];
print(z);
type(z)

[71 86 14]


numpy.ndarray

In [42]:
j = x[np.array([1,3,4,2,7])]
print(j)
type(j)

[92 71 60 14 86]


numpy.ndarray

#### Access rows in 2d array

In [3]:
arr = np.empty((6, 4))
for i in range(6):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [6]:
arr[[4, 3, 0, 5]]

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

## Array masking

In [48]:
np.random.seed(10)
ar=np.random.randint(0,25,10); ar      # 隨機產生10個0~25的整數

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [49]:
evenMask=(ar%2==0); evenMask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [50]:
evenNums=ar[evenMask]; evenNums  # true的值才會出現

array([ 4,  0, 16,  8,  0])

To eliminate missing values

In [51]:
ar=np.array(['Hungary','Nigeria','Guatemala','','Poland','','Japan']); ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'],
      dtype='<U9')

In [52]:
ar[ar=='']='USA'; ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'],
      dtype='<U9')

## Copies and views

<b>Modifying view modifies original array</b>

In [53]:
ar1=np.arange(12); ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
ar2=ar1[::2]; ar2

array([ 0,  2,  4,  6,  8, 10])

In [55]:
ar2[1]=-1 
print(ar2) 
print(ar1)     # ar1也會一起被修改

[ 0 -1  4  6  8 10]
[ 0  1 -1  3  4  5  6  7  8  9 10 11]


<b>Use np.copy to force a copy</b><br>

In [56]:
ar=np.arange(8); ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
arc=ar[:3].copy(); arc

array([0, 1, 2])

In [58]:
arc[0]=-1; arc

array([-1,  1,  2])

In [59]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

## Lab

<b>有一個 7x4 的陣列，每一列代表一個人的資料，人名放在 names 的陣列<br>
試著取得 Will 的資料如下<br>
```
array([[ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843]])
```
</b>

In [3]:
# every row of data corresponding to index of names
np.random.seed(20)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [5]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [62]:
data

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644]])

In [63]:
names == "Will"

array([False, False,  True, False,  True, False, False])

In [64]:
data[names == "Will"]

array([[ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843]])

<b>有兩個陣列分別為 x 與 x_sub，試著將 x_sub 的 [0,0] 改為 99，查看 x 陣列是否有改變?</b>

In [65]:
np.random.seed(0)
x = np.random.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [66]:
x_sub = x[:2, :2]
x_sub

array([[5, 0],
       [7, 9]])

In [100]:
x_sub[0,0] = 99
x_sub

array([[99,  0],
       [ 7,  9]])

In [101]:
x

array([[99,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]])

<b>請取出如下圖示的值
<details>
    <img src='./img/array_slice.png'>
</details>

In [103]:
arr = np.array([[ 0,  1,  2,  3,  4,  5],
                [10, 11, 12, 13, 14, 15],
                [20, 21, 22, 23, 24, 25],
                [30, 31, 32, 33, 34, 35],
                [40, 41, 42, 43, 44, 45],
                [50, 51, 52, 53, 54, 55]])
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [120]:
orange_arr = arr[0,3:5];orange_arr

array([3, 4])

In [121]:
red_arr = arr[:,2];red_arr

array([ 2, 12, 22, 32, 42, 52])

In [122]:
green_arr = arr[2::2,::2];green_arr

array([[20, 22, 24],
       [40, 42, 44]])

In [123]:
lime_arr = arr[4:,4:];lime_arr

array([[44, 45],
       [54, 55]])