In [26]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [75]:
df = pd.DataFrame([['green', 'M', 10.1, 'class1'], ['red','L', 13.5, 'class2'], ['blue', 'XL', 15.3, 'class1']])
df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

#### 透過字典自行編碼

In [76]:
size_mapping = {'XL': 3, 'L': 2, 'M': 1}
df['size'] = df['size'].map(size_mapping); df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

####  Label Encoding : 較適合應用在原始資料是有序離散值

In [77]:
lb_e = LabelEncoder()                                
X = df[['color', 'size', 'price']].values; print(X, end="\n--------------------\n")
X[:, 0] = lb_e.fit_transform(X[:, 0]); print(X)

[['green' 1 10.1]
 ['red' 2 13.5]
 ['blue' 3 15.3]]
--------------------
[[1 1 10.1]
 [2 2 13.5]
 [0 3 15.3]]


In [78]:
y = class_le.fit_transform(df['classlabel'])             # 把classlabel欄位進行標籤編碼
print(y)
print(class_le.inverse_transform(y.reshape(3,)))         # 把classlabel欄位取消編碼

[0 1 0]
['class1' 'class2' 'class1']


#### One Hot Encoding : 較適合應用在原始資料是無序離散值


In [89]:
oh_e = OneHotEncoder()
z = oh_e.fit_transform(df[['color','price']]).toarray()   # 單熱編碼後資料型態是scipy.sparse.csr.csr_matrix，所以要轉乘array 
print(z, end="\n--------------------\n")
print(ohe.inverse_transform(z))

[[0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]
--------------------
[['green' 10.1]
 ['red' 13.5]
 ['blue' 15.3]]


In [80]:
print(np.hstack((ohe.fit_transform(df[['color','price']]).toarray(), df.iloc[:,1:3].values)))

[[ 0.   1.   0.   1.   0.   0.   1.  10.1]
 [ 0.   0.   1.   0.   1.   0.   2.  13.5]
 [ 1.   0.   0.   0.   0.   1.   3.  15.3]]


In [81]:
print(pd.get_dummies(df[['color', 'size', 'price']]))     # get_dummies() 只會將字串轉換成單熱編碼

   size  price  color_blue  color_green  color_red
0     1   10.1           0            1          0
1     2   13.5           0            0          1
2     3   15.3           1            0          0
